#############################################################################
##         _    _
##    _ __| | _| |
##   | '__| |/ / |   Richard Klein Leugemors
##   | |  |   <| |   https://www.github.com/leugemors/
##   |_|  |_|\_\_|
##
##   Configuration for Alacritty, the GPU enhanced terminal emulator
##
#############################################################################

[general]
import = [
    # "~/.config/alacritty/fonts.toml",
    # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
    # "~/.config/alacritty/themes/themes/cool_night.toml",
    # ~/.config/alacritty/themes/themes/dracula_plus.toml",
    # "~/.config/alacritty/themes/themes/rose_pine.toml",
    "~/.config/alacritty/themes/themes/tokyo_night.toml",
    # "~/.config/alacritty/keybindings.toml",
]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

# [colors.primary]
# background = "#000000"

[font]
size = 12.0

[font.offset]
x = 0
y = 0

[font.normal]
style = "Regular"
# family = "JetBrainsMono Nerd Font Mono"
# family = "JetBrainsMono Nerd Font Mono"
# family = "JetBrainsMono Nerd Font Mono"
# family = "JetBrainsMono Nerd Font Mono"
# family = "JetBrainsMono Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
# family = "JetBrainsMono Nerd Font Mono"
# family = "JetBrainsMono Nerd Font Mono"
# family = "JetBrainsMono Nerd Font Mono"
# family = "JetBrainsMono Nerd Font Mono"
# family = "JetBrainsMono Nerd Font Mono"

[scrolling]
history = 5000

[window]
blur = true
decorations = "None"    # (Full, Transparent, Buttonless, None)
dynamic_padding = true
opacity = 1.00

[window.padding]
x = 5
y = 5

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

### eof #####################################################################
