#############################################################################
##         _    _
##    _ __| | _| |
##   | '__| |/ / |   Richard Klein Leugemors
##   | |  |   <| |   https://www.github.com/leugemors/
##   |_|  |_|\_\_|
##
##   Configuration for Alacritty, the GPU enhanced terminal emulator
##
#############################################################################

# For some odd reason I need to set half te value of the font size I want
[font]
size = 12.0 

[font.offset]
x = 0
y = 0

[font.normal]
# style = "Regular"
# family = "3270 Nerd Font"
# family = "BlexMono Nerd Font"
# family = "ComicShanns Nerd Font"
# family = "FiraCode Nerd Font"
# family = "Iosevka Nerd Font"
# family = "Hack Nerd Font"
family = "JetBrains Mono Nerd Font"
# family = "Literation Mono Nerd Font"
# family = "MesloLGL Nerd Font"
# family = "RobotoMono Nerd Font"
# family = "Space Mono Nerd Font"
# family = "Ubuntu Mono Nerd Font"

### eof #####################################################################
